### ISSUE TITLE
added path length calculation

### ISSUE THREAD

**Issue by baiti01** [pyplati/platipy#194] opened 2023-02-06 22:03 UTC
I am a little bit confused about this line (https://github.com/pyplati/platipy/blob/0b34857ec7a6e85742bb7d8c6c51a10d13ea2b3a/platipy/imaging/label/comparison.py#L373):
        added_path = sitk.MaskNegated(label_test_contour, label_ref_contour)

The result should be all the pixels in the label_test_contour while NOT in the label_ref_contour, correct? However, the definition of APL should be all the pixels in the label_ref_contour while NOT in the label_test_contour, correct?

For example, let's say the label_ref_contour is a circle, the label_test_contour only contains the left half of the circle, and the above-calculated added_path will be zero. However, the added path length should be the pixel count of all the pixels in the right half of the circle?

**Comment by pchlap** [comment] 2023-02-09 01:03
Thanks for posting @baiti01. I will let @rnfinnegan comment on specifically what was intended on this line of code.

I will add that I am not super confident in how well this APL code is working. I will work on getting in some tests using some synthetic data to confirm that it is really doing what's intended.

**Comment by rnfinnegan** [comment] 2023-02-09 02:13
Hi @baiti01, thanks for raising this issue!

I think there might be some confusion here because the APL is computed from _contours_, not _masks_. The APL function converts masks to contours, i.e. for each slice finds all the pixels on the edge of the mask.

The definition of the APL from [Vaasen et al. (2019)](https://doi.org/10.1016/j.phro.2019.12.001) is: 

> The path length of a contour that had to be added to meet the institutional guidelines for contouring was calculated by considering all manual adjustments in terms of pixels added, both expansion and shrinkage of the automatically generated contour.

One way to extend/interpret this definition for our more general use case of comparing two contours is:

> The path length of the "test" contour that is not in agreement with the "reference" contour. 

Considering this, we need to include only the regions of the `label_test_contour` that are **not** in agreement with `label_ref_contour`. We define the threshold of this agreement as 3 mm (by default, it can be changed by varying `distance_threshold_mm`.

We do not consider regions of the 'label_ref_contour' that are not in agreement with `label_test_contour` (as you suggested). This was a choice we made based on the original definition of the APL, which adds up the lengths of the contour regions in the "test" label and doesn't consider lengths of the contour regions in the "reference" contour.

To use your example: the APL will not be zero, and will be equal to the length of the region of the half-circle contour that is not in agreement with the full-circle contour (see picture below). 

![demo_circles](https://user-images.githubusercontent.com/16299474/217699298-0769615c-2ea6-497a-8a3e-e5d124ba05b4.png)

I hope this helps, let me know if you have any follow up questions 🚀

**Comment by baiti01** [comment] 2023-02-09 04:37
I am still not entirely agreeing with you. According to the definition of APL, we need to "considering all manual adjustments in terms of pixels added," where "all manual adjustments" means adjusting the label_test_contour to the label_reference_contour. Specific to the above figures, the physician needs to add the yellow region based on the blue (test) region, such as the resultant contour is the label_ref_contour.

The green contour (added pixels) doesn't make sense since the adjusted contour is still NOT the desired reference contour.

Therefore, I feel we may need to revise line 370 as:
`label_ref_contour = sitk.BinaryDilate(label_test_contour, kernel)
`

And line 373 as:
`added_path = sitk.MaskNegated(label_ref_contour, label_test_contour) 
`

**Comment by rnfinnegan** [comment] 2023-02-09 21:52
Yes, I can see your reasoning. I agree with this definition and that we should change the definition of the APL metric. 

Just to confirm, are you suggesting line 370 should be:
`label_test_contour = sitk.BinaryDilate(label_test_contour, kernel)`
(In your example you are overwriting `label_ref_contour`).

Thanks for bringing this issue up - I'll work with @pchlap to implement the changes and make sure the metric is tested appropriately! We can close this issue once the changes are merged.

**Comment by baiti01** [comment] 2023-02-09 22:25
Oooops, typo. Thanks, it should be label_test_contour in line 370.

**Comment by pchlap** [comment] 2023-03-01 02:23
This has been fixed in release v0.6.0

**Closed by pchlap** 2023-03-01 02:23 UTC
